version: '3.8'
services:
  mcp-api:
    network_mode: bridge
    image: ghcr.io/eric2788/mcp-proxy-server:feat-webui
    #build: .
    ports:
      - "3006:3006"  # SSE server
    environment:
      - NODE_ENV=production
      - KEEP_SERVER_OPEN=1
      - WEB_URL=http://localhost:3000
      - JWT_SECRET=your_jwt_secret_here
      - ADMIN_PASSWORD=password
    volumes:
      - ./config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["npm", "run", "start:sse"]
    restart: unless-stopped

  mcp-web:
    network_mode: bridge
    image: ghcr.io/eric2788/mcp-proxy-server:feat-webui
    #build: .
    ports:
      - "3000:3000"  # Next.js app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://mcp-api:3006/api
    command: ["npm", "run", "start:app"]
    restart: unless-stopped